# Generated by Django 3.1.1 on 2020-09-05 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_tweeted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweeted', to=settings.AUTH_USER_MODEL),
        ),
    ]
